apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Parcial1-PAA
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GreenLuimonade/Parcial1-PAA
    path: "."
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: app